# Run cfgcrypt on this file to see how it is encrypted
serverSettings:
        port: 8080
        hostname: localhost
database: # database configuration
        driver: mysqldb
        port: 3306
        user: myAppUser
        ## password to encrypt
        password: #{{password123}}#
vendorApi:
        url: https://www.vendor.com
        key: #{{APIKEY1234567890}}#
